image: node:18.18.0

before_script:
- npm install

pages:
  script:
  - npm run build
  artifacts:
    paths:
    - public
  tags:
  - Pages
  only:
  - main

# image: alpine:latest

# pages:
#   stage: deploy
#   script:
#     - echo "Deploying..."
#   artifacts:
#     paths:
#       - public
#   tags:
#     - Pages
#   only:
#     - main

