image: alpine:latest

pages:
  image: node:v18.18.0
  stage: deploy
  script:
  - npm cache clear --force
  - npm install
  - unset CI
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - main

# image: alpine:latest

# pages:
#   stage: deploy
#   script:
#     - echo "Deploying..."
#   artifacts:
#     paths:
#       - public
#   tags:
#     - Pages
#   only:
#     - main

